# This is a basic workflow to help you get started with Actions
name: Publish image to ACR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    frontend_build:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Publish frontend image
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: distankbregistry.azurecr.io/distankb-map
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: distankbregistry.azurecr.io
          dockerfile: Dockerfile

    backend_build:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Publish frontend image
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: distankbregistry.azurecr.io/distankb-map
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: distankbregistry.azurecr.io
          workdir: distankb.Api/Distankb.Api
          dockerfile: Dockerfile
  
